added random to isawthat.js
VijayStroup/frodo pull request #16
Opened 2022-07-11 18:39 UTC by MrJay-exe

2022-07-11 19:18 UTC, VijayStroup requested changes

2022-07-11 19:18 UTC, VijayStroup commented on events/iSawThat.js
> +const ignored = ['864311867765686332', '369212248553422850','609330932431716353']
only leave the id of `864311867765686332` in the ignored list.

2022-07-11 19:18 UTC, VijayStroup commented on events/iSawThat.js
> +    if(coin){
format like `if (coin) {`

2022-07-11 19:18 UTC, VijayStroup commented on events/iSawThat.js
>      if (ignored.includes(message.author.id)) return
indent line 11 and 12 with 2 spaces.

2022-07-11 19:40 UTC, MrJay-exe commented
Alright changed it with the latest commit

2022-07-11 21:54 UTC, VijayStroup requested changes

2022-07-11 21:54 UTC, vijaystroup commented on events/iSawThat.js
> +      if (ignored.includes(message.author.id)) return
Put the ignored check after the bot check so in the case it is an ignored user, we don't perform the coin computation and just return from the function.

2022-08-25 22:07 UTC, VijayStroup commented on events/iSawThat.js
> +      if (ignored.includes(message.author.id)) return
updates? 👀

2022-08-25 22:08 UTC, VijayStroup commented
closing due to breaking change now.

2022-08-25 22:08 UTC, closed without merging